Towards fixing AAC for relations
Added example about relations in Tutorial.v
Added universe annotations in AAC.v

Normally the modification in Tutorial.v would not require the
two instances. (Note that moving the acc_union_Proper instance
to Instances.v also works.) But even though aac_union_Assoc is
already in Instances.v, removing either instance in Tutotial.v
would result in this error:

Error: aac_tactics: Cannot infer a default A operator (required at least
to be Proper and Associative)

Removing either of the two universe annotations in AAC.v results in a
universe constraint error at Qed in Tutorial.v:

The 1st term has type
"Type@{max(Set+1,Coq.Relations.Relation_Definitions.1)}"
which should be coercible to "Type@{AAC_tactics.AAC.265}".